# code generated by gemini AI

import tkinter as tk
from tkinter import messagebox
import random

class ComputerLogic:
    """Manages board state and Minimax AI with adjustable difficulty."""
    def __init__(self):
        self.board = [None] * 9
        self.difficulty = "Easy"

    def reset_logic(self):
        self.board = [None] * 9

    def check_winner(self, board=None):
        b = board if board else self.board
        win_conditions = [(0,1,2), (3,4,5), (6,7,8), (0,3,6), (1,4,7), (2,5,8), (0,4,8), (2,4,6)]
        for a, b_idx, c in win_conditions:
            if b[a] and b[a] == b[b_idx] == b[c]:
                return b[a]
        return "Tie" if None not in b else None

    def minimax(self, board, depth, is_maximizing):
        res = self.check_winner(board)
        if res == "O": return 1
        if res == "X": return -1
        if res == "Tie": return 0

        if is_maximizing:
            best_score = -float('inf')
            for i in range(9):
                if board[i] is None:
                    board[i] = "O"
                    score = self.minimax(board, depth + 1, False)
                    board[i] = None
                    best_score = max(score, best_score)
            return best_score
        else:
            best_score = float('inf')
            for i in range(9):
                if board[i] is None:
                    board[i] = "X"
                    score = self.minimax(board, depth + 1, True)
                    board[i] = None
                    best_score = min(score, best_score)
            return best_score

    def get_move(self):
        available = [i for i, s in enumerate(self.board) if s is None]
        
        # Easy Mode: 50% chance of making a random mistake
        if self.difficulty == "Easy" and random.random() < 0.5:
            return random.choice(available)

        best_score = -float('inf')
        move = None
        for i in available:
            self.board[i] = "O"
            score = self.minimax(self.board, 0, False)
            self.board[i] = None
            if score > best_score:
                best_score = score
                move = i
        return move

class TicTacToeGUI:
    """Handles 400x400 Canvas, Scoreboard, and UX."""
    def __init__(self, root):
        self.root = root
        self.root.title("Pro Tic-Tac-Toe")
        self.logic = ComputerLogic()
        self.scores = {"Player": 0, "Computer": 0, "Ties": 0}

        # Score Display
        self.score_label = tk.Label(root, text="Player: 0 | Computer: 0 | Ties: 0", font=("Arial", 12, "bold"))
        self.score_label.pack(pady=5)

        # Board
        self.canvas = tk.Canvas(root, width=400, height=400, bg="white")
        self.canvas.pack()
        self.canvas.bind("<Button-1>", self.handle_click)

        # Difficulty Toggle
        self.diff_var = tk.StringVar(value="Easy")
        tk.Radiobutton(root, text="Easy (Beatable)", variable=self.diff_var, value="Easy", command=self.set_diff).pack(side="left", padx=20)
        tk.Radiobutton(root, text="Hard (Optimal)", variable=self.diff_var, value="Hard", command=self.set_diff).pack(side="left")

        # Reset Button
        tk.Button(root, text="Reset Board", command=self.reset_game, bg="lightgrey").pack(pady=10)
        self.draw_grid()

    def set_diff(self):
        self.logic.difficulty = self.diff_var.get()

    def draw_grid(self):
        for i in range(1, 3):
            self.canvas.create_line(i*133, 0, i*133, 400, width=2)
            self.canvas.create_line(0, i*133, 400, i*133, width=2)

    def draw_mark(self, index, player):
        r, c = divmod(index, 3)
        x, y = c * 133 + 66, r * 133 + 66
        if player == "X":
            self.canvas.create_line(x-40, y-40, x+40, y+40, fill="red", width=6)
            self.canvas.create_line(x+40, y-40, x-40, y+40, fill="red", width=6)
        else:
            self.canvas.create_oval(x-40, y-40, x+40, y+40, outline="blue", width=6)

    def handle_click(self, event):
        idx = (event.y // 133) * 3 + (event.x // 133)
        if self.logic.board[idx] is None:
            self.logic.board[idx] = "X"
            self.draw_mark(idx, "X")
            if self.process_turn(): return

            comp_idx = self.logic.get_move()
            self.logic.board[comp_idx] = "O"
            self.draw_mark(comp_idx, "O")
            self.process_turn()

    def process_turn(self):
        res = self.logic.check_winner()
        if res:
            if res == "X": self.scores["Player"] += 1
            elif res == "O": self.scores["Computer"] += 1
            else: self.scores["Ties"] += 1
            
            self.score_label.config(text=f"Player: {self.scores['Player']} | Computer: {self.scores['Computer']} | Ties: {self.scores['Ties']}")
            messagebox.showinfo("Game Over", f"Result: {res if res == 'Tie' else res + ' Wins!'}")
            self.reset_game()
            return True
        return False

    def reset_game(self):
        self.logic.reset_logic()
        self.canvas.delete("all")
        self.draw_grid()

if __name__ == "__main__":
    app = tk.Tk()
    TicTacToeGUI(app)
    app.mainloop()